apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  labels:
    app: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: django-app:latest
        envFrom:
          - configMapRef:
              name: django-app
        imagePullPolicy: Never
        ports:
          - containerPort: 80
